version: "3.8"

services:
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped
        tty: true
        container_name: mail-import-php
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=lara_polcar_items
            - DB_USERNAME=user
            - DB_PASSWORD=secret
            
    nginx:
        image: nginx:latest
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"  
            - "443:443" 
        links:
            - php-fpm
        depends_on:
            - php-fpm
        container_name: mail-import-nginx
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            
    db:
        image: mysql:8.0
        volumes:
            - mail-import_dbdata:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=user"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=lara_polcar_items"
        ports:
            - "3306:3306"  
        container_name: mail-import-db
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          timeout: 20s
          retries: 10
          
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8085:80"  
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: secret
            UPLOAD_LIMIT: 128M
        container_name: mail-import-admin
        
    node:
        build:
            context: .
            dockerfile: ./docker/nodejs/Dockerfile
        ports:
            - "5173:5173"  
        volumes:
            - .:/var/www            
        working_dir: /var/www
        tty: true
        container_name: mail-import-node
        environment:
            - NODE_ENV=development

volumes:
    mail-import_dbdata:
        driver: local